### PR TITLE
Keeping read-only behavior as optional

### PR DESCRIPTION
**Pull request by andrevitor103**
Hello @dg how are you? We had some issues with the last update where the read-only definition of classes and variables is being removed. I noticed that more people are also having problems with this. I believe that this behavior can be configurable, also thinking about a future where we can have more definitions that can be removed using this library. Here's my suggestion for ignoring tokens that we don't want handled in our tests. Thank you if you can review. Related issue #39 .

### CODE REVIEW

**Comment by dg** [comment]
I think it would be easier for the user to add a parameter to enable():

```php
DG\BypassFinals::enable(bypassReadOnly: false);
```

Alternatively, add a method:

```php
DG\BypassFinals::enable();
DG\BypassFinals::bypassReadOnly(false);
```

**Comment by andrevitor103** [comment]
Good morning @dg, thank you very much, perfect, I tested it here and everything is fine. Would you create a version for us to use?

**Comment by dfostercb911** [comment]
It'd be dope to get a release tag going for master since 1.5.0 still doesn't have the new `enable` parameters to toggle bypasses 😎 . 

Don't listen to me if there is something I'm not aware of heh.

**Comment by dfostercb911** [comment]
Thank you so much @andrevitor103 !!

**Pull request closed without merging**
