### PR TITLE
fix: allow using alternative stream handlers (Infection)

### PR DESCRIPTION
**Pull request by dkarlovi**
This is a PR from comments made by @dg and @maks-rafalko in #9. It's confirmed to fix issues with using Infection and BypassFinals together, tested on two of my projects.

### CODE REVIEW

**Comment by dkarlovi** [comment]
Never mind, I've just noticed master branch contains the fix mentioned by @dg and it works even without the patch made by @maks-rafalko. The fix here seems to be to rely on `dev-master` version until next release. Closing.

**Comment by maks-rafalko** [comment]
Should be reopened, see https://github.com/dg/bypass-finals/issues/9#issuecomment-1236094916

**Comment by dmitryuk** [comment]
Is it possible to make testcase?

**Comment by dkarlovi** [comment]
Agreed, we should try to make one to avoid regressions here. Maybe we register a dummy stream wrapper and then register BypassFinals, would that work?

**Comment by dkarlovi** [comment]
Alternative fix by @dg merged, closing.

**Pull request closed without merging**
